server {

        server_name feature.pranshuaryal.com.np;

        access_log /var/log/nginx/feature.pranshuaryal.com.np-access.log;

        error_log /var/log/nginx/feature.pranshuaryal.com.np-error.log;


        location / {

                proxy_pass http://localhost:3002;

        }


}